---
- name: Create LVM
  hosts: cloudera
  gather_facts: true
  tasks:
    - name: Create LVM
      ansible.builtin.include_role:
        name: linux-create-lvm
      vars:
        vg_name: cloudera_vg
        lv_name: cloudera_lv
        mount_point: /opt
