---
- name: Test_connection
  hosts: "{{ group | default('test') }}"
  gather_facts: true

  tasks:
    - name: Test connection
      ansible.builtin.include_role:
        name: linux/linux_install_docker