---
- name: Test_connection
  hosts: localhost
  connection: local
  gather_facts: true

  tasks:
  - name: Get hostname
    ansible.builtin.debug:
      msg: "{{ hostvars[inventory_hostname]['ansible_nodename'] }}"