---
- name: Install Packages
  ansible.builtin.package:
    name:
      - confluent-server
    state: present

- name: Update Config File
  block:
    - name: Transfer Config File
      ansible.builtin.template:
        src: zookeeper.properties.j2
        dest: /etc/kafka/zookeeper.properties
        mode: "0644"
    - name: Set Zookeeper Ids
      ansible.builtin.blockinfile:
        path: /etc/kafka/zookeeper.properties
        block: |
          server.{{ hostvars[item]['ansible_default_ipv4']['address'].split('.')[3] }}={{ hostvars[item]['ansible_default_ipv4']['address'] }}:2888:3888
        marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item }}"
      with_items: "{{ groups['zookeeper'] }}"

- name: Set myid
  ansible.builtin.copy:
    content: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'].split('.')[3] }}"
    dest: /var/lib/zookeeper/myid
    mode: "0755"
- name: Start Zookeeper
  ansible.builtin.systemd:
    name: confluent-zookeeper
    state: restarted
    enabled: true
