---
- name: Setup Repository
  ansible.builtin.copy:
    src: "confluent.repo"
    dest: "/etc/yum.repos.d/confluent.repo"
    mode: "0644"

- name: Install Zookeeper
  when: "'zookeeper' in group_names"
  ansible.builtin.include_tasks: install_zk.yaml

- name: Install and Configure Broker
  when: "'broker' in group_names"
  ansible.builtin.include_tasks: install_broker.yaml

- name: Configure Broker Authentication
  ansible.builtin.include_tasks: config_auth.yaml

- name: Install and Configure Control Center
  when: "'control-center' in group_names"
  ansible.builtin.include_tasks: install_control_center.yaml

- name: Configure Metadata Service
  ansible.builtin.include_tasks: config_mds.yaml
