---
- name: Setup Repository
  ansible.builtin.copy:
    src: "confluent.repo"
    dest: "/etc/yum.repos.d/confluent.repo"
    mode: "0644"

- name: Install Dependencies
  ansible.builtin.package:
    name:
      - java-1.8.0-openjdk
    state: present

- name: Install Zookeeper
  when: "'zookeeper' in group_names"
  ansible.builtin.include_tasks: install_zk.yaml

- name: Set Variable
  block:
    - name: List ZK hosts
      ansible.builtin.set_fact:
        zookeeper_url_list: "{{ zookeeper_url_list | default([]) + [hostvars[item]['ansible_nodename'] + ':2181'] }}"
      loop: "{{ groups['zookeeper'] }}"
    - name: List Schema Registry Hosts
      ansible.builtin.set_fact:
        schema_registry_url_list: "{{ schema_registry_url_list | default([]) + ['http://' + hostvars[item]['ansible_nodename'] + ':8081'] }}"
      loop: "{{ groups['registry'] }}"

    - name: Export Zookeeper URLs
      ansible.builtin.set_fact:
        schema_registry_url: "{{ schema_registry_url_list | join(',') }}"
        zookeeper_url: "{{ zookeeper_url_list | join(',') }}"

- name: Install and Configure Broker
  when: "'broker' in group_names"
  ansible.builtin.include_tasks: install_broker.yaml

- name: Enable Metadata Service
  ansible.builtin.include_tasks: config_mds.yaml
  when: "'broker' in group_names"

- name: Install Schema Registry
  when: "'registry' in group_names"
  ansible.builtin.include_tasks: install_schema_registry.yaml

- name: Add Schema Registry URL(s) to Broker
  when: "'broker' in group_names"
  block:
    - name: Add Registry URLs
      ansible.builtin.lineinfile:
        line: "confluent.schema.registry.url={{ schema_registry_url }}"
        path: "/etc/kafka/server.properties"
        state: present
    - name: Restart Service
      ansible.builtin.systemd:
        name: confluent-server
        state: restarted

- name: Install and Configure Control Center
  when: "'control-center' in group_names"
  ansible.builtin.include_tasks: install_control_center.yaml
