---
- hosts: test 
  gather_facts: no 
  vars:
    download_url: https://edelivery.oracle.com/osdc/softwareDownload?fileName=V982063-01.zip&token=Si9tMm0xUTkwS0FTZm1wWDN5RitOUSE6OiFmaWxlSWQ9MTA0NDg4MDA2JmZpbGVTZXRDaWQ9OTAxMzc3JnJlbGVhc2VDaWRzPTg5NDk4MiZwbGF0Zm9ybUNpZHM9MzUmZG93bmxvYWRUeXBlPTk1NzY0JmFncmVlbWVudElkPTc2Mjg3MDkmZW1haWxBZGRyZXNzPXN1cHBvcnRAYm5oLnZuJnVzZXJOYW1lPUVQRC1TVVBQT1JUQEJOSC5WTiZpcEFkZHJlc3M9MTAzLjIxLjE0OC4xNDAmdXNlckFnZW50PU1vemlsbGEvNS4wIChNYWNpbnRvc2g7IEludGVsIE1hYyBPUyBYIDEwXzE1XzcpIEFwcGxlV2ViS2l0LzUzNy4zNiAoS0hUTUwsIGxpa2UgR2Vja28pIENocm9tZS85MC4wLjQ0MzAuMjEyIFNhZmFyaS81MzcuMzYmY291bnRyeUNvZGU9Vk4mZGxwQ2lkcz0xMDQzNjc4
    sso_user: support@bnh.vn
    sso_passwd: BNHdba@2020
    sso_cookie: /tmp/wget_oracle_sso
    remote_user: root
    oracle_base: /opt/oracle
    oracle_home: /opt/oracle/product/19.0.0/dbhome_1
    ora_inventory: /opt/oraInventory
    data_dir: /opt/oracle/oradata
    oracle_sid: orcl
  tasks:
    - name: Download software
      block:
        - name: login
          shell: wget  --secure-protocol=auto --save-cookies="{{ sso_cookie }}" --keep-session-cookies  --http-user "{{ sso_user }}" --password "{{ sso_passwd }}" "https://edelivery.oracle.com/osdc/cliauth" -O /dev/null
        - name: download
          shell: wget  --load-cookies="{{ sso_cookie }}" "{{ download_url }}" -O "/tmp/oracle.zip"
      when: download_software == true
    - name: Configure OS
      block:
        - name: edit hosts file 
          block:
            - name: get hostname
              shell: hostname
              args:
                executable: /bin/bash
              register: hostname
            - name: get IP
              shell: hostname -I |sed -e "s| |\n|g"|grep -v "\.1$"
              args:
                executable: /bin/bash
              register: IPes
            - debug:
                var: hostname.stdout
            - debug:
                var: IPes
            - name: edit file
              blockinfile:
                path: /etc/hosts
                backup: yes
                block: |
                  {{ item }}   {{ hostname.stdout }}
              loop:
                - "{{ IPes.stdout_lines }}"
        - name: sysctl
          block:
            - name: update sysctl parameter
              blockinfile: 
                path: /etc/sysctl.conf
                backup: yes
                block: |
                  fs.file-max = 6815744
                  kernel.sem = 250 32000 100 128
                  kernel.shmmni = 4096
                  kernel.shmall = 1073741824
                  kernel.shmmax = 4398046511104
                  kernel.panic_on_oops = 1
                  net.core.rmem_default = 262144
                  net.core.rmem_max = 4194304
                  net.core.wmem_default = 262144
                  net.core.wmem_max = 1048576
                  net.ipv4.conf.all.rp_filter = 2
                  net.ipv4.conf.default.rp_filter = 2
                  fs.aio-max-nr = 1048576
                  net.ipv4.ip_local_port_range = 9000 65500
            - name: apply params
              shell: /sbin/sysctl -p
        - name: security limits
          blockinfile:
            path: /etc/security/limits.d/oracle-database-preinstall-19c.conf
            backup: yes 
            block: |
              oracle   soft   nofile    1024
              oracle   hard   nofile    65536
              oracle   soft   nproc    16384
              oracle   hard   nproc    16384
              oracle   soft   stack    10240
              oracle   hard   stack    32768
              oracle   hard   memlock    134217728
              oracle   soft   memlock    134217728
            # create: true
        - name: YUM 
          ansible.builtin.yum:
            name:
              - bc
              - binutils
              - compat-libcap1
              - compat-libstdc++-33
              - dtrace-modules
              - dtrace-modules-headers
              - dtrace-modules-provider-headers
              - dtrace-utils
              - elfutils-libelf
              - elfutils-libelf-devel
              - fontconfig-devel
              - glibc
              - glibc-devel
              - ksh
              - libaio
              - libaio-devel
              - libdtrace-ctf-devel
              - libXrender
              - libXrender-devel
              - libX11
              - libXau
              - libXi
              - libXtst
              - libgcc
              - librdmacm-devel
              - libstdc++
              - libstdc++-devel
              - libxcb
              - make
              - net-tools 
              - nfs-utils 
              - python 
              - python-configshell 
              - python-rtslib 
              - python-six 
              - targetcli 
              - smartmontools
              - sysstat
              - unixODBC
    #     - name: create groups
    #       group: 
    #         name: oinstall
    #         gid: 54321
    #       group: 
    #         name: dba
    #         gid: 54322
    #       group: 
    #         name: oper
    #         gid: 54323
    #       group:
    #         name: backupdba
    #         gid: 54324
    #       group:
    #         name: dgdba
    #         gid: 54325
    #       group:
    #         name: kmdba
    #         gid: 54326
    #       group:
    #         name: asmdba
    #         gid: 54327
    #       group:
    #         name: asmoper
    #         gid: 54328
    #       group:
    #         name: asmadmin
    #         gid: 54329
    #       group:
    #         name: racdba
    #         gid: 54330
    #     - name: create user 
    #       user:
    #         name: oracle
    #         password: 'oracle_4U'
    #         groups:
    #           - oinstall
    #           - dba
    #           - oper
    #         state: present
    #         shell: /bin/bash
    #         createhome: yes
    #     - name: SELinux
    #       block:
    #         - name: check config
    #           shell: getenforce
    #           args:
    #             executable: /bin/bash
    #           register: selinux_status
    #         - name: set config
    #           shell: setenforce 0 && sed -i -e "s|SELINUX=enforcing|SELINUX=permissive|g" /etc/selinux/config
    #           args:
    #             executable: /bin/bash
    #           when: selinux.stdout == "Enforcing"
    #     - name: disable firewalld
    #       shell: systemctl stop firewalld && systemctl disable firewalld
    #       args: 
    #         var: /bin/bash
    # - name: Install Oracle Database 
    #   block:
    #     - name: create directories
    #       ansible.builtin.file:
    #         path: "{{ item }}"
    #         state: directory
    #         owner: oracle
    #         group: oinstall 
    #         mode: 0775
    #       loop:
    #         - "{{ oracle_home }}"
    #         - "{{ ora_inventory }}"
    #         - "{{ data_dir }}"
    #     - name: extract software
    #       ansible.builtin.unarchive:
    #         src: /tmp/oracle.zip
    #         dest: "{{ oracle_home }}"
    #         remote_src: yes
    #     - name: run installer
    #       shell:
    #         cmd: |
    #           "{{ oracle_home }}"/runInstaller -ignorePrereq -waitforcompletion -silent \
    #           -responseFile "{{ oracle_home }}"/install/response/db_install.rsp \
    #           oracle.install.option=INSTALL_DB_SWONLY \
    #           ORACLE_HOSTNAME="{{ hostvars[inventory_hostname] }}" \
    #           UNIX_GROUPNAME=oinstall \
    #           INVENTORY_LOCATION="{{ ora_inventory }}"  \
    #           SELECTED_LANGUAGES=en,en_GB  \
    #           ORACLE_HOME="{{ oracle_base }}  \
    #           ORACLE_BASE="{{ oracle_home }}  \
    #           oracle.install.db.InstallEdition=EE  \
    #           oracle.install.db.OSDBA_GROUP=dba  \
    #           oracle.install.db.OSBACKUPDBA_GROUP=dba  \
    #           oracle.install.db.OSDGDBA_GROUP=dba  \
    #           oracle.install.db.OSKMDBA_GROUP=dba  \
    #           oracle.install.db.OSRACDBA_GROUP=dba  \
    #           SECURITY_UPDATES_VIA_MYORACLESUPPORT=false  \
    #           DECLINE_SECURITY_UPDATES=true
    #       become: true
    #       become_user: oracle              


