---
- name: get remote file serial 
  ansible.builtin.slurp:
    src: "/var/named/{{ db_file }}"
  register: remotedbfile

- name: copy db file
  ansible.builtin.copy:
    src: "{{ db_file }}"
    dest: "/var/named/{{ db_file }}"
    mode: "0644"

- name: update serial 
  ansible.builtin.lineinfile:
    path: "/var/named/{{ db_file }}"
    regexp: ' *([0-9]+).*; Serial'
    line: "   {{ ((remotedbfile['content'] | b64decode | regex_findall(' *([0-9]+).*; Serial') |first) |int) +1 }} ; Serial"

- name: restart named service
  ansible.builtin.systemd:
    name: named 
    state: restarted
    enabled: yes 