---
- name: Install Dependencies
  ansible.builtin.yum:
    name: 
      - "{{ fuse_overlayfs }}"
      - "{{ lirp4netns }}"
      - "{{ fuse3_libs }}"
      - "{{ container_selinux }}"
      - "yum-utils"
    state: present 
- name: Setup Repository 
  ansible.builtin.yum_repository:
    name: docker 
    description: Docker Stable Version 
    baseurl: https://download.docker.com/linux/centos/$releasever/$basearch/stable
    enabled: yes
    gpgcheck: no 
- name: Install Docker 
  ansible.builtin.yum:
    name: 
      - docker-ce 
      - docker-ce-cli
      - containerd.io
    state: present 
- name: start docker
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: yes 