---
- name: Install & configure httpd
  block:
    - name: install httpd
      ansible.builtin.yum:
        name:
          - httpd
        state: present
    - name: Start httpd
      ansible.builtin.systemd:
        state: started
        name: httpd
        enabled: yes 

- name: Configure Repository
  block:
    - name: create repo directory 
      ansible.builtin.file:
        path: /var/www/html/{{ repo_name }}
        state: directory
        owner: root 
        group: root 
        mode: '0755'
    - name: extract tarball
      ansible.builtin.unarchive:
        src: "{{ tarball.stdout }}"
        dest: /var/www/html/{{ repo_name }}
        remote_src: yes
        owner: root 
        group: root
        list_files: True
      register: file_list
    - name: get repo path 
      ansible.builtin.find:
        path: /var/www/html/{{ repo_name }}
        file_type: directory
        recurse: yes
        patterns: "repodata"
      register: dir_matches
    - name: create repo
      ansible.builtin.yum_repository:
        name: "{{ repo_name }}" 
        description: "{{ repo_name }}" 
        baseurl: "http://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}/{{ dir_matches.files[0].path | dirname | regex_replace('/var/www/html/','') }}"
        enabled: yes
        gpgcheck: no 
