---
- name: get configuration variables 
  block: 
    - name: buffer pool size 
      shell: free -g |grep Mem| awk '{print $2}'
      register: mem_total

- name: backup old configuration 
  block: 
    - name: copy file 
      copy: 
        remote_src: true 
        src: /etc/my.cnf 
        dest: /etc/my.cnf.OLD
    - name: remove my.cnf
      ansible.builtin.file: 
        path: /etc/my.cnf
        state: absent

- name: Set MySQL Configurations 
  ansible.builtin.blockinfile:
    path: /etc/my.cnf
    create: yes
    block: | 
      bind-address = 0.0.0.0
      socket = /tmp/mysqld.sock
      datadir = {{ datadir }}
      lower-case-table-names = 1
      innodb-buffer-pool-size = {{ (mem_total.stdout * 0.5) | int }}
      error-log = {{ error_log }}

      # replication
      log-bin = {{ binlog_dir }}
      expire-log-days = {{ expire_log_days }}
      gtid-mode = on 
      enforce-gtid-consistency = on 
      server-id = {{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] | regex_replace('([0-9]{1,3}\.){2}([0-9]*)\.([0-9]*)$', '\\2\\3') }}
