---
- name: create staging directory
  block: 
    - name: setup directory
      ansible.builtin.file:
        name: /tmp/oim-scheduled-tasks/lib
        state: directory
        mode: 0644
    - name: create plugin.xml
      ansible.builtin.template:
        src: plugin.xml.j2
        dest: /tmp/oim-scheduled-tasks/plugin.xml
        mode: 0644
- name: build jar file 
  ansible.builtin.debug:
    msg: #TODO  using mvn package

- name: create scheduled task archive # noqa command-instead-of-shell no-changed-when
  ansible.builtin.shell: "zip -r {{ plugin_zip }} /tmp/oim-scheduled-tasks"

- name: cleanup staging dir 
  block:
    - name: get file list
      ansible.builtin.find:
        paths: 
          - /tmp/oim-scheduled-tasks
          - "{{ plugin_zip }}"
      register: file_list

    - name: delete files 
      ansible.builtin.file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ file_list.files }}"

- name: upload code
  block:
    - name: upload ant.properties
      ansible.builtin.template:
        src: ant.properties.j2
        dest: "{{ mw_home }}/idm/server/plugin_utility/ant.properties"
        mode: 0755

    - name: execute plugin registration # noqa command-instead-of-shell no-changed-when
      ansible.builtin.shell: "ant -f { mw_home }}/idm/server/plugin_utility/pluginregistration.xml register"

- name: register metadata
  block:
    - name: create staging dir
      ansible.builtin.file:
        name: /tmp/oim-metadata/db
        state: directory
        mode: 0755
    - name: copy metadata file
      ansible.builtin.file:
        src: "{{ metadata_file }}"
        dest: "/tmp/oim-metadata/db/{{ metadata_file }}"
        mode: 0755
        remote_src: no
    - name: register metadata  # noqa command-instead-of-shell no-changed-when
      ansible.builtin.shell: "java -jar importScheduledTaskMetadata.jar -h {{ oim_hostname }} -P {{ oim_port }} -u {{ xelsysadm_username }} -p {{ xelsysadm_passwd }} -f /tmp/oim-metadata/db/{{ metadata_file }}"