---
- name: download package
  ansible.builtin.include_role:
    name: oracle_MOS_download
  vars:
    download_dest: /tmp/ggs_mysql.zip
    download_file_checksum: 5b3b3ff1f792c0012b08ac44abb911e1f25ab145  
- name: create OGG OS group
  ansible.builtin.group:
    name: "{{ ogg_os_group }}"
    state: present
- name: create OGG user 
  ansible.builtin.user:
    name: "{{ ogg_os_user }}"
    state: present
    shell: /bin/bash
    groups: "{{ ogg_os_group }}"
    append: yes 
- name: update bash profile 
  ansible.builtin.blockinfile:
    path: "/home/{{ ogg_os_user }}/.bash_profile"
    insertafter: EOF
    block: |
      export ORACLE_BASE={{ oracle_base }}
      export OGG_HOME={{ oracle_home }}
      export ORACLE_HOME={{ oracle_home }}
      export PATH=$PATH:$ORACLE_HOME
- name: create directories 
  ansible.builtin.file:
    path: "{{ oracle_home }}"
    state: directory
    mode: 0750
    owner: "{{ ogg_os_user }}"
    group: "{{ ogg_os_group }}"