--- 
- name: unzip download file
  ansible.builtin.unarchive:
    src: "{{ download_dest }}"
    dest: /tmp/
    remote_src: yes 
    owner: root
    group: root
    mode: 0755
- name: install jdk
  ansible.builtin.yum:
    name: /tmp/jdk-8u301-linux-x64.rpm
    state: present
- name: set default JAVA_HOME
  ansible.builtin.blockinfile:
    path: /etc/bashrc
    block: |
      export JAVA_HOME=/usr/java/latest
      export PATH=$JAVA_HOME/bin:$PATH